namespace Data.Databases.Csversion1;

public partial class Tag : BaseModel
{
    public int Id { get; set; }

    public string? Type { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? Webname { get; set; }

    public string? Imagename { get; set; }

    public int? Catalogueid { get; set; }

    public int? Accesslevel { get; set; }

    public DateTime Created { get; set; }

    public int Autogenerated { get; set; }

    public int Priority { get; set; }

    public DateTime Lastmodified { get; set; }
}

